### ISSUE TITLE
홈페이지 퍼블리싱 컨텐츠 합의

### ISSUE THREAD

**Issue by jams777** [chatbus/chatbus_hompage#1]
홈페이지 퍼블리싱을 진행

컨텐츠는 구성원 합의하에 진행함

**Comment by jams777** [comment]
@chatbus/homepage 어떠한 내용으로 진행하면 좋을까요??

**Comment by jams777** [comment]
프로젝트 기본 설명은 있었으면..

**Comment by jams777** [comment]
멤버들 정보도 있었으면...

**Comment by jams777** [comment]
라이센스 정책도 보이고, 깃허브도 링크로 연결되면 좋겠어요

**Comment by jams777** [comment]
기능목록도 있고~ 나중엔 설치 메뉴얼도 있었으면 해요

**Comment by thgml21004** [comment]
자주 묻는 질문도 있으면 좋겠어요.
몇명이 우리 홈페이지를 타고 왔는지 설정도 해줬으면 좋겠어요.
그래서 몇명이 채팅화면을 사용했는지도요

**Comment by jams777** [comment]
추가로 더 넣었으면 하는게 있을까요??

@thgml21004 @ghdl023 @CheonInJeong

**Comment by jams777** [comment]
다들 합의한걸로 하고 이대로 하시지요~
