### ISSUE TITLE
멤버 정보 화면 데이터 분리

### ISSUE THREAD

**Issue by thgml21004** [chatbus/chatbus_hompage#17]
멤버 정보 데이터 분리 작업해주세요.

**Comment by jams777** [comment]
@CheonInJeong 
컨텐츠가 바뀐다고 화면개발 소스나 컴포넌트를 바꾸는건 아니고 데이터만 바꾸게 하는게 좋아요~
여기선 튜토리얼을 따라서 mdx 파일로 해보죠~

**Comment by jams777** [comment]
@thgml21004 @CheonInJeong 
멤버 정보에 어떤게 보이면 좋을까요?  
. 이름
. 대표사진(프로필)
. 별명
. 소개 문구 
---- 아래는 개발자가 자주 애용하는 것...
. 깃허브주소
. 트위터
. 링크드인
. 개인홈페이지
. 참여 프로젝트 또는 회사, 조직

**Comment by CheonInJeong** [comment]
이름(별명)
대표사진
소개문구
깃허브주소
개인홈페이지(노션,블로그 등등?)
참여 프로젝트 
링크드인

이렇게?ㅎㅎ 근데 사실 소개가 들어가면 어떻게 써야할지 많은 고민을 하게 될 것 같아요ㅎㅎ

**Comment by jams777** [comment]
. 나는 ㅇㅇㅇ 개발자입니다.
. 나는 ㅇㅇㅇ 개발이 목표입니다.
. ㅇㅇㅇ 을 위해 개발합니다.
. 새로운 배움을 좋아하는 개발자입니다.

이런 정도로 1-3 문장 정도로만 간단하게 넣으면 부담이 되지 않을것 같아요~

**Comment by jams777** [comment]
이름(별명)
대표사진
소개문구
깃허브주소
개인홈페이지(노션,블로그 등등?)
참여 프로젝트
링크드인

이렇게 하고 정보는 각자 PR 을 하시죠~

**Comment by jams777** [comment]
@CheonInJeong 첸첸님 개발하시다가 필요한 플러그인이나 라이브러리 있으면
도커 안에 /app/web2 ( alias app2 ) 에서 추가해서 테스트 해보시고 요청해주시면 
도커안에 넣어놓겠습니다.~ 필요한거 편하게 이야기해주세요~
