### ISSUE TITLE
각자 자기 소개 한줄씩 넣어주세요.

### ISSUE THREAD

**Issue by jams777** [chatbus/chatbus_hompage#28]
@CheonInJeong 님이 데이터 넣을 수 있게 만들어 주셨어요~

각자 소개 한줄씩 넣어주세요~ ^^

연결가능한 프로필 있으시면 추가해주고요~~

**Comment by jams777** [comment]
https://github.com/chatbus/chatbus_homepage/tree/issue-28

브랜치 생성해놨어요~~

**Comment by thgml21004** [comment]
@jams777 
제 소개는 추가해서 푸쉬했습니다~

**Comment by jams777** [comment]
저도 추가해서 PR 했습니다.
