### ISSUE TITLE
IE(Information Architecture) 설계 - 메뉴구조 정하기

### ISSUE THREAD

**Issue by jams777** [chatbus/chatbus_hompage#3]

**Comment by jams777** [comment]
메뉴구조부터 잡으면 레이아웃 잡기 쉬울것 같습니다.

**Comment by jams777** [comment]
대표화면은 프로젝트 설명하고,
팀원 소개는 대메뉴로 해서 누가 만들었는지 보이면 어떨까요??? 
FAQ도 대메뉴로 해도 될듯하구요...

**Comment by CheonInJeong** [comment]
|- 프로젝트 소개(라이센스 정책, 깃허브링크)
|- 멤버 정보(담당역할-> 한 페이지로 소개?하위메뉴로 소개?🤔)
|- 기능목록
(|- 설치메뉴얼)
|- FAQ

이런식으로 하면 될까요? 방문자나 사용자 수는 상단에 고정으로 보여주는게 좋을 것 같습니다!
(알람이 안와서 늦게 본 점 죄송합니다🥲)

**Comment by thgml21004** [comment]
사용자 수는 블로그나 카페처럼 메인 화면에 조그만한게 표시해주면 좋을것 같아요.
라이센스 정책은 하단 footer로 빼는게 나을까요?

**Comment by jams777** [comment]
> 

늦게 봐도 됩니다. ^^ 편하게 같이 이야기 해요~
시간되면 하시고 일정 신경 쓰지 말구 즐겁게 만들어봐요~

**Comment by jams777** [comment]
팀원들은 한페이지로 간단하게만 소개하면 좋을듯해요~
기능 목록이랑 메뉴얼은 아직 없으니 커밍순~~~

**Comment by jams777** [comment]
이번주까지만 같이 이야기해보고 다음주부터 의견나온거 대로 모아서 진행해봐요~

참고로 IE 는 사용자 중심으로 생각해보는게 중요합니다.

**Comment by jams777** [comment]
|- 프로젝트 소개(라이센스 정책, 깃허브링크)
|- 멤버 정보
|- 메뉴얼(설치,기능목록 포함)
|- FAQ

**Comment by jams777** [comment]
이렇게 정리하고 갑니다.~ 앞으로 수정해가면서 바꿔봐요~
