### ISSUE TITLE
화면 레이아웃 결정하기

### ISSUE THREAD

**Issue by jams777** [chatbus/chatbus_hompage#4]
정해진 컨텐츠랑 메뉴구조에 맞게 레이아웃을 결정해봅시다~

**Comment by jams777** [comment]
전 헤더랑 푸터가 있으면 좋을듯해요~

**Comment by jams777** [comment]
헤더엔 대메뉴....
메뉴얼만 좌측에 TOC 형태로 중메뉴가 있으면 될듯하고
나머진 랜딩페이지 형태로 되면 좋을것 같은데...
푸터엔 그냥 깃허브로 연결되서 라이센스도 깃허브에서 보이면 좋을듯하구요~

**Comment by thgml21004** [comment]
toc형태가 뭔지 모르겠어요..
헤더에 메뉴랑 로고가 같이 들어가면 좋겠네요.
좌측에 로고랑 메뉴 넣던가 아님 좌측에 로고 넣고 가운데에 메뉴 넣기

**Comment by jams777** [comment]
https://en.wikipedia.org/wiki/Table_of_contents

목차형태로 좌측에 매뉴얼 제목들이 보이고 해당 제목들 클릭하면 우측에 해당 설명 위치로 이동하는 형태에요~
매뉴얼 사이트에서 많이 사용하는 형태에요. 
위키에서도 보면 최상단에 contents 라고 박스로 목차가 표시되는데 이런걸 우린 좌측정도에 중메뉴처럼 넣으면 되지 않을까 싶어서..

**Comment by jams777** [comment]
그럼 헤더에 메뉴랑 로고...
```
---------------------------------
로고      |     메뉴들
---------------------------------
컨텐츠 ( 매뉴얼에는 목차가 좌측에 메뉴형태로 보이게 )
---------------------------------
푸터
---------------------------------
```
이렇게 진행해봐요~
