### ISSUE TITLE
무료 테마중 디자인 정하기

### ISSUE THREAD

**Issue by jams777** [chatbus/chatbus_hompage#6]
무료 테마 사이트를 리서치하여 디자인 정하기

예) https://onepagelove.com/templates/free-templates

**Comment by thgml21004** [comment]
https://play-tailwind.tailgrids.com/

다양한 상세 페이지가 있어서 작업하기 괜찮을것 같아요.
똑같은 페이지를 Bootstrap이랑 Tailwind css 스타일로 작업한게 있는데 작업 안해본 Tailwind css로 해보는게 좋을것 같습니다.

**Comment by jams777** [comment]
상업적인것까지 쓸수 있네요....
우리도 드디어 Tailwind css 해보게 되네요...
