### ISSUE TITLE
디자인에 맞춰 레이아웃 퍼블리싱 하기

### ISSUE THREAD

**Issue by jams777** [chatbus/chatbus_hompage#7]
https://play-tailwind.tailgrids.com/

이걸로 레이아웃 컴포넌트에 퍼블리싱 하기~

**Comment by jams777** [comment]
이슈이름으로 브랜치를 만들고 있습니다.
작업 후에 해당 브랜치를 PR( Pull requests ) 해주세요~

**Comment by jams777** [comment]
@thgml21004 레이아웃작업(#5 )이 완료(#8 )되었네요...
issue-7 브랜치는 예전 main 에서 따온거라 한번 update 받고 작업해야합니다.~

**Comment by thgml21004** [comment]
@jams777 도커에 이 라이브러리 추가해주세요

`
yarn add -D tailwindcss postcss autoprefixer gatsby-plugin-postcss
`

**Comment by jams777** [comment]
@thgml21004  (#15) 라이브러리 추가 되었습니다.~

**Comment by thgml21004** [comment]
@jams777 

홈페이지 작업 완료해서 PR 했는데 확인해주세요
스크립트는 결국 적용 못하고 딱 화면만 우선 완료했네요ㅎㅎ
